openapi: "3.0.0"
info:
  title: "Kurumsal Yönetim Platformu API"
  version: "1.0.0"
servers:
  - url: http://localhost:3000/api
paths:
  /auth/register:
    post:
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:   { type: string }
                email:  { type: string }
                password:{ type: string }
                role:   { type: string }
      responses:
        '201': { description: Kullanıcı kayıt edildi }
  /auth/login:
    post:
      tags: [Auth]
      requestBody:
        ... // benzer şekilde tanımlayın
